### ISSUE TITLE
final-touch

### ISSUE THREAD

**Issue by Sayed94h** [murvanessa/todolist-wk-3#15]
## 6. Finishing Touches

- Validate code to check for any last mistakes

**Assigned to Sayed**

- \_Given [context] when [a specific action is performed] then [a set of consequences should occur]\_\_
- ...

### REPO

- This user story is developed on branch `final-touch`.
- This branch is merged to `master` branch after completion.

### Task A: JavaScript

- [x] edited the following code in the function `displayItems`

```js
if (todo.completed === true) {
	checkItem.checked = true;
} else {
	checkItem.checked = false;
}
```

- [x] Created a new function `toggleComplete`

```js
	toggleComplete(todo) {
		debugger;
		todo.completed = !todo.completed;
		this.displayItems();
	}
```

- [x] fixed a simple mistake inside of the class `List`

### Task B: CSS

- [x] Added background for the web page

### Task C: wireframe

- [x] Created a simple wireframe and added to the development-strategy

### Task D: Development Strategy

- [x] Wrote the final part of the development strategy

### Task E: PR

- [x] Created PR and assigned reviewers

### Task F: issue

- [x] Created issue for this part of the project

### Task G:

- [x] Validate HTML, CSS, ...

---
