### ISSUE TITLE
TodoList-container

### ISSUE THREAD

**Issue by Sayed94h** [murvanessa/todolist-wk-3#5]
### Task A: Style

- [x] style for title input box
- [x] style for item input box
- [x] style for add button
- [x] style for list container

### Task B:  HTML

- [x] placeholder for title input box

### Task C: JavaScript

- [x] Added `div tag`
- [x] Added `h2 tag`
- [x] Added `input tag`
- [x] Added `button tag`
- [x] Added attributes to each `tag`
